micronaut:
  application:
    name: api
  server:
    port: 8080
    cors:
      enabled: true
  security:
    enabled: true
    authentication: bearer
    endpoints:
      login:
        enabled: true
    token:
      jwt:
        enabled: true
        generator:
          access-token:
            expiration: 86400
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET}
              base64: true
              jws-algorithm: HS512
couchbase:
  url: ${COUCHBASE_URL}
  user: ${COUCHBASE_USER}
  password: ${COUCHBASE_PASSWORD}
datasources:
  default:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
jpa:
  default:
    packages-to-scan:
      - 'poupix.person.dal.model'
      - 'poupix.account.dal.model'
      - 'poupix.payment.dal.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: none